version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: connectup-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=connectup

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: connectup-backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/connectup
      - JWT_SECRET=your_jwt_secret_key_here
      - JWT_EXPIRE=7d
      - FRONTEND_URL=http://localhost:3000
      - OPENAI_API_KEY=your_openai_api_key

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: connectup-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongodb_data: 